config/routes.rb
Rails.application.routes.draw do
  # devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create]
  resources :videos, only: [:new, :index, :destroy]
  root 'videos#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  before_create -> { self.uid = generate_uid }

  private

  def generate_uid
    loop do
      uid = Digest::MD5.hexdigest(self.created_at.to_s + rand(10000).to_s)
      return uid unless User.exists?(uid: uid)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery with: :exception
  # before_action :authenticate_user!
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end

  def create
    User.create(username:user_params)
    redirect_to '/'
  end

  private

  def user_params
    params.permit(:username)
  end

end

app/controllers/videos_controller.rb
class VideosController < ApplicationController

  def index
    ziggeo = Ziggeo.new(ENV['ZIGGEO_KEY'], ENV['ZIGGEO_SECRET'], ENV['ZIGGEO_ENCRYPTION'])
    @videos = ziggeo.videos.index
  end

  def new
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ZigZag</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="//assets-cdn.ziggeo.com/v1-stable/ziggeo.css" />
    <script src="//assets-cdn.ziggeo.com/v1-stable/ziggeo.js"></script>
    <script>ZiggeoApi.token = '<%= ENV['ZIGGEO_KEY'] %>';</script>
  </head>

  <body>
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>">
        <%= value %>
      </div>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<form class="new-user" action="/users" method="post">
        <input type="text" name="username" placeholder="name">
        <button>Sign Up</button>
    </form>

app/views/videos/_video.html.erb
<div class="card">
  <div class="card-block">
    <ziggeo ziggeo-video='<%= video['token'] %>'
            ziggeo-width="320"
            ziggeo-height="240" ziggeo-popup>
    </ziggeo>
</div>

app/views/videos/index.html.erb
<h1>Videos</h1>

<%= link_to 'Add video', new_video_path %>

<%= render partial: 'video', collection: @videos, as: :video %>

app/views/videos/new.html.erb
<ziggeo ziggeo-limit="60"
        ziggeo-width="320"
        ziggeo-height="240"
        ziggeo-perms="allowupload"></ziggeo>
<progress class="progress progress-striped hidden-xs-up" value="0" max="100"></progress>